### ISSUE TITLE
Implement controller layer.

### ISSUE THREAD

**Issue by VincentPeters** [undefinedio/stash#13]
# Problem
- Wordpress doesn't have a proper controller layer
- Theme root folder is polluted with lots of templating files
# Solution
- Abstract a layer between Wordpress template hierarchy and Timber views
- Remove this layer from the theme root.
# Template hierarchy

![image](https://cloud.githubusercontent.com/assets/400738/10029172/deeeae3e-6170-11e5-9db4-7e0bd3a67dcf.png)
# Technical achievement
- Remove all theme files from Theme root except "index.php"
- Load in a Controller routing class inside index.php
- Recreate WP template hierarchy inside this new Controller router
- Search for matching controllers inside a specific controller folder (/Stash/controllers/)
- Each controller inherent from a main controller
- provide a fallback when no specific controller are found

Thoughts? @simonpeters @koraysels @benjamindemoor

**Comment by simonpeters** [comment]
Are these controllers going to be plain php files or classes?

**Comment by simonpeters** [comment]
Are these controllers going to be plain php files or classes?

**Comment by VincentPeters** [comment]
I think classes are preferred, then they can inherent from a parent Class

**Comment by simonpeters** [comment]
:+1:

**Comment by VincentPeters** [comment]
Added
