### ISSUE TITLE
add yarn instead of npm?

### ISSUE THREAD

**Issue by VincentPeters** [undefinedio/stash#59]
https://auth0.com/blog/five-things-you-can-do-with-yarn/?utm_source=facebookgroups&utm_medium=sc&utm_campaign=yarn

**Comment by simonpeters** [comment]
Ziet er Nice uit.

Op za 15 okt. 2016 10:26 schreef Vincent Peters notifications@github.com:

**Comment by VincentPeters** [comment]
Done
